
import React, { useState } from 'react';
import Header from './components/Header.tsx';
import Footer from './components/Footer.tsx';
import WorkoutForm from './components/WorkoutForm.tsx';
import WorkoutChart from './components/WorkoutChart.tsx';
import { UserData, WorkoutPlan } from './types.ts';
import { generateWorkoutPlan } from './services/geminiService.ts';

const App: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [workoutPlan, setWorkoutPlan] = useState<WorkoutPlan | null>(null);

  const handleGeneratePlan = async (userData: UserData) => {
    setLoading(true);
    setError(null);
    try {
      const plan = await generateWorkoutPlan(userData);
      setWorkoutPlan(plan);
      setTimeout(() => {
        document.getElementById('results')?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    } catch (err) {
      console.error(err);
      setError('An error occurred while generating your plan. Please ensure your API key is configured correctly.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      
      <main className="flex-grow max-w-7xl mx-auto px-4 py-8 md:py-12 w-full">
        <div className="max-w-4xl mx-auto">
          {!workoutPlan && (
            <div className="text-center mb-12">
              <h2 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-4">
                Your Peak Performance <span className="text-indigo-600 italic">Starts Here</span>
              </h2>
              <p className="text-lg text-slate-500">
                Fill out the form below to receive a personalized, data-driven workout chart generated by AI to match your specific needs and goals.
              </p>
            </div>
          )}

          <div className="space-y-12">
            <section className="no-print">
              <WorkoutForm onSubmit={handleGeneratePlan} isLoading={loading} />
            </section>

            {error && (
              <div className="bg-red-50 border border-red-200 p-4 rounded-xl text-red-700 flex items-center gap-3 no-print">
                <i className="fas fa-circle-exclamation"></i>
                {error}
              </div>
            )}

            {workoutPlan && (
              <section id="results" className="pt-8">
                <WorkoutChart plan={workoutPlan} />
                
                <div className="mt-12 text-center no-print">
                  <button 
                    onClick={() => {
                      setWorkoutPlan(null);
                      window.scrollTo({ top: 0, behavior: 'smooth' });
                    }}
                    className="text-indigo-600 font-semibold hover:text-indigo-800 transition-colors"
                  >
                    <i className="fas fa-arrow-left mr-2"></i> Start Over / Modify Inputs
                  </button>
                </div>
              </section>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default App;
